// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken string `json:"access_token"`
	Errror      string `json:"error"`
}

type InfoRequest struct {
	Name string `json:"name"`
}

type InfoResponse struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Gender string `json:"gender"`
}

type GetAll struct {
}

type ResponseGetAll struct {
	Id     int64  `db:"id"`
	Email  string `db:"email"`
	Name   string `db:"name"`
	Gender string `db:"gender"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Gender   string `json:"gender"`
}

type RegisterResponse struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Gender string `json:"gender"`
}

type DeleteRequest struct {
}

type DeleteResponse struct {
}

type UpdateRequest struct {
	Password string `json:"password"`
	Email    string `json:"email"`
	Gender   string `json:"gender"`
}

type UpdateResponse struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Gender string `json:"gender"`
}
